/* This file is autogenerated from the database. */
/* See src/desc/gen_proto */
/* Do not edit*/
entree functions_default[]={
{"TeXstyle",0,(void*)sd_TeXstyle,16,"",""},
{"colors",0,(void*)sd_colors,16,"",""},
{"compatible",0,(void*)sd_compatible,16,"",""},
{"datadir",0,(void*)sd_datadir,16,"",""},
{"debug",0,(void*)sd_debug,16,"",""},
{"debugfiles",0,(void*)sd_debugfiles,16,"",""},
{"debugmem",0,(void*)sd_debugmem,16,"",""},
{"factor_add_primes",0,(void*)sd_factor_add_primes,16,"",""},
{"factor_proven",0,(void*)sd_factor_proven,16,"",""},
{"format",0,(void*)sd_format,16,"",""},
{"histsize",0,(void*)sd_histsize,16,"",""},
{"log",0,(void*)sd_log,16,"",""},
{"logfile",0,(void*)sd_logfile,16,"",""},
{"nbthreads",0,(void*)sd_nbthreads,16,"",""},
{"new_galois_format",0,(void*)sd_new_galois_format,16,"",""},
{"output",0,(void*)sd_output,16,"",""},
{"parisize",0,(void*)sd_parisize,16,"",""},
{"path",0,(void*)sd_path,16,"",""},
{"prettyprinter",0,(void*)sd_prettyprinter,16,"",""},
{"primelimit",0,(void*)sd_primelimit,16,"",""},
{"realprecision",0,(void*)sd_realprecision,16,"",""},
{"secure",0,(void*)sd_secure,16,"",""},
{"seriesprecision",0,(void*)sd_seriesprecision,16,"",""},
{"simplify",0,(void*)sd_simplify,16,"",""},
{"sopath",0,(void*)sd_sopath,16,"",""},
{"strictargs",0,(void*)sd_strictargs,16,"",""},
{"strictmatch",0,(void*)sd_strictmatch,16,"",""},
{"threadsize",0,(void*)sd_threadsize,16,"",""},
{NULL,0,NULL,0,NULL,NULL} /* sentinel */
};
