/* This file is autogenerated from the database. */
/* See src/desc/gen_proto */
/* Do not edit*/
entree functions_gp_default[]={
{"breakloop",0,(void*)sd_breakloop,16,"",""},
{"echo",0,(void*)sd_echo,16,"",""},
{"graphcolormap",0,(void*)sd_graphcolormap,16,"",""},
{"graphcolors",0,(void*)sd_graphcolors,16,"",""},
{"help",0,(void*)sd_help,16,"",""},
{"histfile",0,(void*)sd_histfile,16,"",""},
{"lines",0,(void*)sd_lines,16,"",""},
{"linewrap",0,(void*)sd_linewrap,16,"",""},
{"prompt",0,(void*)sd_prompt,16,"",""},
{"prompt_cont",0,(void*)sd_prompt_cont,16,"",""},
{"psfile",0,(void*)sd_psfile,16,"",""},
{"readline",0,(void*)sd_readline,16,"",""},
{"recover",0,(void*)sd_recover,16,"",""},
{"timer",0,(void*)sd_timer,16,"",""},
{NULL,0,NULL,0,NULL,NULL} /* sentinel */
};
