/* This file is autogenerated from the database. */
/* See src/desc/gen_proto */
/* Do not edit*/
entree functions_gp[]={
{"alarm",0,(void*)gp_alarm,11,"D0,L,DE","alarm({s = 0},{code}): if code is omitted, trigger an \"e_ALARM\" exception after s seconds, cancelling any previously set alarm; stop a pending alarm if s = 0 or is omitted. Otherwise, evaluate code, aborting after s seconds."},
{"allocatemem",0,(void*)allocatemem0,11,"vDG","allocatemem({s=0}): allocates a new stack of s bytes. doubles the stack if s is omitted."},
{"breakpoint",0,(void*)pari_breakpoint,11,"v","breakpoint(): interrupt the program and enter the breakloop. The program continues when the breakloop is exited."},
{"dbg_down",0,(void*)dbg_down,11,"vD1,L,","dbg_down({n=1}): (break loop) go down n frames. Cancel a previous dbg_up."},
{"dbg_err",0,(void*)dbg_err,11,"","dbg_err(): (break loop) return the error data of the current error, if any."},
{"dbg_up",0,(void*)dbg_up,11,"vD1,L,","dbg_up({n=1}): (break loop) go up n frames. Allow to inspect data of the parent function."},
{"extern",0,(void*)extern0,11,"s","extern(str): execute shell command str, and feeds the result to GP (as if loading from file)."},
{"externstr",0,(void*)externstr,11,"s","externstr(str): execute shell command str, and returns the result as a vector of GP strings, one component per output line."},
{"input",0,(void*)input0,11,"","input(): read an expression from the input file or standard input."},
{"quit",0,(void*)gp_quit,11,"vD0,L,","quit({status = 0}): quit, return to the system with exit status 'status'."},
{"read",0,(void*)read0,11,"D\"\",s,","read({filename}): read from the input file filename. If filename is omitted, reread last input file, be it from read() or \\r."},
{"readstr",0,(void*)readstr,11,"D\"\",s,","readstr({filename}): returns the vector of GP strings containing the lines in filename."},
{"system",0,(void*)system0,11,"vs","system(str): str being a string, execute the system command str."},
{"whatnow",0,(void*)whatnow0,11,"vr","whatnow(key): if key was present in GP version 1.39.15 or lower, gives the new function name."},
{NULL,0,NULL,0,NULL,NULL} /* sentinel */
};
